# ********************************
# VRX backpack targets
# ********************************

[env:VRX_ESP8285_Backpack_via_UART]
extends = env_common_esp8285, full_vrx_backpack_common
upload_resetmethod = nodemcu
build_flags =
	${env_common_esp8285.build_flags}
	${full_vrx_backpack_common.build_flags}
	-D PIN_LED=16
	-D PIN_MOSI=12	;Some pin (not a UART)
	-D PIN_CLK=0 	;Boot pad
	-D PIN_CS=15	;Some other pin (not a UART)
	-D PIN_SDA=2
	-D PIN_SCL=14
	-D PIN_INT=13
reset_method=nodemcu
lib_deps =
	${full_vrx_backpack_common.lib_deps}

[env:VRX_ESP8285_Backpack_via_WIFI]
extends = env:VRX_ESP8285_Backpack_via_UART

[env:VRX_ESP32_Backpack_via_UART]
extends = env_common_esp32, full_vrx_backpack_common
upload_resetmethod = nodemcu
build_flags =
	${env_common_esp32.build_flags}
	${full_vrx_backpack_common.build_flags}
	-D PIN_LED=2
	-D PIN_MOSI=18	;Some pin (not a UART)
	-D PIN_CLK=19 	;Boot pad
	-D PIN_CS=5	    ;Some other pin (not a UART)
lib_deps =
	${full_vrx_backpack_common.lib_deps}
	deneyapkart/Deneyap Servo @ 1.0.7

[env:VRX_ESP32_Backpack_via_WIFI]
extends = env:VRX_ESP32_Backpack_via_UART

[env:VRX_C3_Backpack_via_UART]
extends = env_common_esp32c3, full_vrx_backpack_common
build_flags =
	${env_common_esp32c3.build_flags}
	${full_vrx_backpack_common.build_flags}
	-D PIN_BUTTON=9
	-D PIN_SDA=2
	-D PIN_SCL=3
	-D PIN_INT=4
	-D PIN_MOSI=5
	-D PIN_CLK=6
	-D PIN_CS=7
monitor_filters = esp32_exception_decoder
monitor_speed = 460800
lib_deps =
	${full_vrx_backpack_common.lib_deps}
	deneyapkart/Deneyap Servo @ 1.0.7

[env:VRX_C3_Backpack_via_WIFI]
extends = env:VRX_C3_Backpack_via_UART

[env:VRX_S3_Backpack_via_UART]
extends = env_common_esp32s3, full_vrx_backpack_common
build_flags =
	${env_common_esp32s3.build_flags}
	${full_vrx_backpack_common.build_flags}
	-D PIN_BUTTON=0
	-D PIN_SDA=11
	-D PIN_SCL=12
	-D PIN_INT=13
	-D PIN_MOSI=5
	-D PIN_CLK=6
	-D PIN_CS=7
monitor_filters = esp32_exception_decoder
monitor_speed = 460800
board_upload.flash_size=4MB
lib_deps =
	${full_vrx_backpack_common.lib_deps}
	deneyapkart/Deneyap Servo @ 1.0.7

[env:VRX_S3_Backpack_via_WIFI]
extends = env:VRX_S3_Backpack_via_UART
